COMP: Windows frame info initialization
Intended to address:

  D:\a\ITKIOOpenJPH\ITKIOOpenJPH\src\itkOpenJPHImageIO.cxx(288): error C7555: use of designated initializers requires at least '/std:c++20'